### PR TITLE
Fixes for old SciPy version

### PR DESCRIPTION
**Pull request by mscroggs**
This fixes issue #282

### CODE REVIEW

**Comment by mscroggs** [comment]
Some unittests still fail. Closing this pull request until fixed

**Comment by jenshnielsen** [comment]
@mscroggs the tests in Jenkins are know to be broken at the moment so don't pay to much attention to them

**Comment by mscroggs** [comment]
Local unit tests fail too though!

**Comment by jenshnielsen** [comment]
Ok, just want to make sure that you are not waisting your time with Jenkins

**Comment by mscroggs** [comment]
All unit tests now pass on my old version of SciPy.

@tbetcke Can you check that tests still pass, then merge and close #282?

**Pull request merged**
